ARG BALENA_MACHINE_NAME="%%BALENA_MACHINE_NAME%%"

FROM balenalib/${BALENA_MACHINE_NAME}-debian:buster
RUN install_packages bluez-tools bluez iptables bridge-utils
RUN install_packages python3 python3-dbus
COPY bluetooth.sh /bluetooth.sh
COPY bluetoothserver.sh /bluetoothserver.sh
COPY bluetoothclient.sh /bluetoothclient.sh
COPY entrypoint.sh /entrypoint.sh
COPY bridge.py /bridge.py

ENV DEVICE hci0

ENTRYPOINT ["/bin/bash", "/entrypoint.sh"]

