ARG BALENA_MACHINE_NAME="%%BALENA_MACHINE_NAME%%"

FROM balenalib/${BALENA_MACHINE_NAME}-debian:buster
RUN install_packages python3

COPY index.html /web/
WORKDIR /web

ENTRYPOINT ["python3", "-m", "http.server", "--bind", "0.0.0.0", "80"]

